[project]
name = "MWAIRuntime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "flask>=3.1.2",
    "g4f>=6.5.7",
    "requests>=2.32.5",
]
